### PR TITLE
Trinket support

### PR DESCRIPTION
**Pull request by wouter173**
Hi there, I liked your grave mod and recently added trinkets to my smp server and noticed your mod didn't have support for trinket slots. 

So I went searching on the internet just to find out all the other grave mods are not to my liking so I added trinket support myself!

I thought you wanted to know since the mod is still actively maintained no pressure on this feature or my code style from your side, just thought I'd like to know if someone forked my mod :) 

Have a nice day!

### CODE REVIEW

**Comment by PneumonoIsNotAvailable** [comment]
Oh woah, thanks!
Am I supposed to do something with this? I'm still very new to modding and even newer to github so I don't really know how everything works yet, sorry.

**Comment by wouter173** [comment]
No, you don't have to do anything. 
But if you want my changes to also apply yo your code you can press the merge button! Pull requests are a way to let open source contributors contribute to any project, It's up to you whether you actually want the code.

**Comment by PneumonoIsNotAvailable** [comment]
Can I take some of the code and implement it differently? Trinkets support is great, but looking at it I'm pretty sure this would make trinkets a mandatory dependency, which is a bit of a problem. I'm fairly sure I know how to fix that, but do I merge the pull request then change it, or copy the code over some other way?

**Comment by wouter173** [comment]
Yes you are absolutely right, trinkets is a mandatory dependency now. 

If you want to reimplement trinket support I'd suggest you close this PR and use it as reference when doing it yourself.
If you want to use my branch as the base I would work further on the fork (my project) and fix it there with another PR.

Personally I would go with the first option.

**Comment by PneumonoIsNotAvailable** [comment]
Okay, thank you for your time and advice!

**Pull request closed without merging**
